version: "3"
services:
  dingtalk:
    build: .
    container_name: dingtalk
    network_mode: host

  alertmanager:
    container_name: alertmanager
    image: quay.io/prometheus/alertmanager
    network_mode: host
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    network_mode: host
    user: root
    # ports:
    #   - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./hoststats-alert.rules:/etc/prometheus/hoststats-alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
