global:
  scrape_interval: 15s
  external_labels:
    origin_prometheus: p1

rule_files:
  - /etc/prometheus/hoststats-alert.rules

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]
